### ISSUE TITLE
Code reviews-changes required.

### ISSUE THREAD

**Issue by sangwa7** [Shubh-Dev/portfolio-setup#9]
### Required changes

1. Semantic html it is not advisable to use ID but class. :wink:

2. It should be much better when use `<section>` tag to the segments of the project that are binded together for clear writing of the code. :blush:

</body>
</html>

3. For the img tag, the alt attribute would be better when it is more descriptive to explain what the image is about.

**Comment by Shubh-Dev** [comment]
test issue
